### ISSUE TITLE
Incorrectly displays the names of Ukrainian

### ISSUE THREAD

**Issue by julia4** [javadev/latintoukrainian#4]
![image](https://cloud.githubusercontent.com/assets/2802740/7865801/eed8c892-0573-11e5-82c6-afb6328b9efe.png)

**Comment by javadev** [comment]
Good catch. Please use ukrainiantolatin converter which is official kmu 2010 recomendation for ukrainian letters. Zoia for Зоя is correct latinic name.

**Comment by julia4** [comment]
![anatolii](https://cloud.githubusercontent.com/assets/2802740/7866907/30a10e5e-057b-11e5-8ce7-99c81bffef13.JPG)
![gennadii](https://cloud.githubusercontent.com/assets/2802740/7866908/30a16796-057b-11e5-9cd3-6c1dd5235789.jpg)
![vitalii](https://cloud.githubusercontent.com/assets/2802740/7866906/309f72ba-057b-11e5-8966-409e8a2380ac.JPG)

**Comment by julia4** [comment]
![lesiya](https://cloud.githubusercontent.com/assets/2802740/7867123/c317d582-057c-11e5-98de-e24e0194ff0a.jpg)
