### ISSUE TITLE
It does not recognize the "ій" at the end of a word

### ISSUE THREAD

**Issue by julia4** [javadev/latintoukrainian#5]
![anatolii](https://cloud.githubusercontent.com/assets/2802740/7868257/5c0c5cc6-0583-11e5-8a37-284ed350fec7.JPG)
![gennadii](https://cloud.githubusercontent.com/assets/2802740/7868255/5c0a4116-0583-11e5-9fc6-39aacfc88813.jpg)
![Uploading Vitalii.JPG…]()

**Comment by javadev** [comment]
Fixed.

![fixed_iy](https://cloud.githubusercontent.com/assets/348496/7868547/8fdb6f90-0585-11e5-8f26-8afe277d340a.PNG)

**Comment by julia4** [comment]
Fixed with PR https://github.com/javadev/latintoukrainian/pull/6
