### ISSUE TITLE
incorrect display of combinations of letters "ій, ться, ої, оїх", the application does not recognize "ь"

### ISSUE THREAD

**Issue by julia4** [javadev/latintoukrainian#9]
Precondition: running program "Latintoukrainian", typing some text: "yakii spilkuiutsia tvoi batky ", 
"tvoikh", "tvoi"

ER: yakii spilkuiutsia tvoi batky - якій спілкуються твої батьки, tvoikh - твоїх, tvoi - твої

AR: yakii spilkuiutsia tvoi batky - якіі спілкуюця твоі батки, tvoikh - твоіх, tvoi - твоі

![text_bagi](https://cloud.githubusercontent.com/assets/2802740/7989425/09953a2a-0af2-11e5-9f69-23ffc17a66eb.png)

**Comment by javadev** [comment]
Fixed.
